[package]
name = "lisp-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib_lisp"
path = "src/lib.rs"

[[bin]]
name = "lisp" 
path = "src/bin/main.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
